name: npm CloudArtifact Demo
on: [push]
      
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with: 
          registry_list: |
            registry=`<npm mirror url>`
            @test:registry=`<npm private repo url>`
          auth_list: |
            //`<npm private repo domain>`:_auth=${{ secrets.NPM_AUTH }}
      - run: |
          npm publish --verbose
