name: npm CloudArtifact Demo
on: [push]
      
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with: 
          registry_list: |
            registry=https://mirrors.huaweicloud.com/repository/npm/
            @test:registry=https://devrepo.devcloud.cn-north-7.ulanqab.huawei.com/artgalaxy/api/npm/xxxx/
          auth_list: |
            //devrepo.devcloud.cn-north-7.ulanqab.huawei.com/artgalaxy/api/npm/xxxx/:_auth=${{ secrets.NPM_AUTH }}
      - run: |
          npm publish --verbose
